version: '3'
services:
  front:
    build:
      context: ./front-End
    ports:
      - '80:80'
  
  back:
    build:
      context: ./back-end
    ports:
      - '3000:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/usr/src/app/recipes.db
  db:
    image: busybox:latest
    volumes:
      - ./back:/usr/src/app  # Mount the entire backend folder
    command: tail -f /dev/null  # Keep the container running
